#define BEGINNING	1
#define BODY		2
#define END			3
#define ADD			4
#define MOVE		5
#define INPUT		6
#define PRINT		7
#define TO			8
#define DOT 		9
#define XXXXX		10
#define XXXX		11
#define XXX			12
#define XX			13
#define X			14
#define DECLARATION 15
#define VARIABLE	16
#define STRING		17
#define DIGIT		18
